# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

warning_are_errors: true
bioc_check: true

r:
- release
- devel
- bioc-devel
